### ISSUE TITLE
Switch to session-only authentication

### ISSUE THREAD

**Issue by kstypik** [kstypik/letteranne#11]
Currently, after https://github.com/kstypik/letteranne/pull/10 we are using JWT for authentication and they are problematic [(1)](https://redis.com/blog/json-web-tokens-jwt-are-dangerous-for-user-sessions/) [(2)](http://cryto.net/~joepie91/blog/2016/06/13/stop-using-jwt-for-sessions/)

Switch over to standard Django sessions which are battle-tested, provide reasonable security and are easy to implement.

Probably dependency on dj-rest-auth should be dropped and custom views should be provided or we can try shoehorning django-allauth into our API needs (see https://github.com/pennersr/django-allauth/issues/360)

**Comment by pennersr** [comment]
FYI: https://github.com/pennersr/django-allauth/issues/360#issuecomment-2009080496
